name: CI-CD main pipeline
on: 
  push:
    branches: ["main", "cicd-setup"]
jobs:
  php-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: PHP-Lint
        uses: J3-Tech/PHP-Lint-Action@v0.0.5
        with:
          path: ./phpBB3
          exclude: ./phpBB3/vendor
  gitleaks-check:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}