name: CI-CD main pipeline
on: 
  push:
    branches: ["main"]
jobs:
  php-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: PHP-Lint
        uses: J3-Tech/PHP-Lint-Action@v0.0.5
        with:
          path: ./phpBB3
          exclude: ./phpBB3/vendor
  gitleaks-check:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-check-docker-container:
    name: Build docker image and scan it for vulnerabilities
    runs-on: ubuntu-latest
    needs: [gitleaks-check, php-linter]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Build docker container
        run: |
          docker build -t docker.io/vodoprovod4ika/devops-final-project:${{ github.sha}} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/vodoprovod4ika/devops-final-project:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL'
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-check-docker-container]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: vodoprovod4ika/devops-final-project:${{ github.sha }}